### PR TITLE
Exposed Folders

### PR DESCRIPTION
**Pull request by Uneo7**
Hi, 

I added a dead simple feature to select the folders you want to expose (see : https://github.com/dianlight/hassio-addons/issues/24).

This adds a the following folders config just a folder to true to expose it:

```yaml
folders:
  config: false
  addons: false
  ssl: false
  share: false
  backup: false
  media: true
```

### CODE REVIEW

**Comment by dianlight** [comment]
Thanks for the PR but there are a few things that need to be changed before the merge.

- We need to keep the backwards compatibility so the default if the new parameters are missing must be "true" not "false".
- It would be nice if the new parameters were documented in DOCS.md
- In case one of the folders is set to false, the MQTT report must be removed. Look at MQTT_daemon.sh.

**Comment by Uneo7** [comment]
[x] Update the doc
[x] Avoid BC break. If the folder key is undefined, it will expose everything. However, if folder is defined, it will expect the exposed folders to de defined.
[] Update MQTT

**Comment by dianlight** [comment]
Hi, the only missing part is the MQTT related. 
Do you plan to add to your PR? The next release is planned for the end of the month.

L.

**Comment by Uneo7** [comment]
Hey, 

I just need to find some time to dig in the MQTT script, I'll try to do it before the next release :)

**Comment by dianlight** [comment]
No more activity.  Same functionality can be obtained with acl parameter in 9.7.0-nas1.

**Pull request closed without merging**
